name: Debug Runner Acquisition

on:
  workflow_dispatch: # 手動で実行できるようにする

jobs:
  test-runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Test Echo
        run: echo "Hello world! Runner was acquired successfully."